package com.republicate.kroom.gradle.l10n

import com.republicate.kroom.webapp.l10n.PoParser
import com.republicate.kroom.webapp.l10n.TemplateTranslator
import com.republicate.kroom.webapp.l10n.TranslationSource
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Translates each template under [templates] into every configured language and emits, into
 * [outputDir]:
 * - `templates/<lang>/<rel>` — the translated Velocity sources (source language: verbatim);
 * - `kotlin/.../Templates.kt` — a `vtlFile` stub per (template, language) plus a `renderPage`
 *   dispatcher, all carrying the consumer's typed scopes as context parameters.
 *
 * The translated trees feed the velocity `templateRoot`; the stubs compile through the velocity K2
 * plugin into typed, per-language render functions — no runtime translation.
 */
abstract class GenerateTranslatedTemplatesTask : DefaultTask() {

    @get:InputDirectory abstract val templates: DirectoryProperty

    @get:InputDirectory @get:Optional abstract val i18n: DirectoryProperty

    @get:Input abstract val sourceLanguage: Property<String>

    @get:Input abstract val languages: ListProperty<String>

    @get:Input @get:Optional abstract val appScope: Property<String>

    @get:Input @get:Optional abstract val sessionScope: Property<String>

    @get:Input @get:Optional abstract val requestScope: Property<String>

    @get:Input abstract val generatedPackage: Property<String>

    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    private data class Stub(val funName: String, val key: String, val vtlPath: String)

    @TaskAction
    fun generate() {
        val out = outputDir.get().asFile
        val templatesOut = File(out, "templates")
        val kotlinOut = File(out, "kotlin")
        out.deleteRecursively()
        templatesOut.mkdirs(); kotlinOut.mkdirs()

        val source = sourceLanguage.get()
        val templatesDir = templates.get().asFile
        val i18nDir = i18n.orNull?.asFile
        val templateFiles = templatesDir.walkTopDown()
            .filter { it.isFile && (it.extension == "html" || it.extension == "vm") }
            .toList()

        val stubs = ArrayList<Stub>()
        for (lang in languages.get()) {
            val translator = TemplateTranslator(translationSource(lang, source, i18nDir), source)
            for (file in templateFiles) {
                val rel = file.relativeTo(templatesDir).invariantSeparatorsPath
                // Translate text (non-source langs) and prefix literal #parse/#include targets with the
                // language, so they resolve within the relocated <lang>/ tree.
                val translated = translator.translate(file.readText(), lang) { "$lang/$it" }
                File(templatesOut, "$lang/$rel").apply { parentFile.mkdirs(); writeText(translated) }
                stubs += Stub(
                    funName = "page_${rel.replace(Regex("[^A-Za-z0-9]"), "_")}_$lang",
                    key = "$lang/$rel",
                    vtlPath = "$lang/$rel"
                )
            }
        }

        val pkg = generatedPackage.get()
        File(kotlinOut, pkg.replace('.', '/')).apply { mkdirs() }
            .resolve("Templates.kt").writeText(renderKotlin(pkg, stubs))
    }

    /** A [TranslationSource] backed by `<i18nDir>/<lang>.po`; empty for the source language. */
    private fun translationSource(lang: String, source: String, i18nDir: File?): TranslationSource {
        val map: Map<String, String> =
            if (lang == source || i18nDir == null) emptyMap()
            else File(i18nDir, "$lang.po").takeIf { it.isFile }?.inputStream()?.use { PoParser.parse(it) } ?: emptyMap()
        return object : TranslationSource {
            override fun getTranslation(en: String, iso: String): String? = if (iso == lang) map[en] else null
            override fun getAllTranslations(iso: String): Map<String, String> = if (iso == lang) map else emptyMap()
            override fun isLoaded(iso: String): Boolean = true
        }
    }

    private fun renderKotlin(pkg: String, stubs: List<Stub>): String {
        // Context-parameter order is precedence: request > session > app.
        val ctxParams = buildList {
            requestScope.orNull?.let { add("request: $it") }
            sessionScope.orNull?.let { add("session: $it") }
            appScope.orNull?.let { add("app: $it") }
        }
        require(ctxParams.isNotEmpty()) { "velocityL10n: at least one of appScope/sessionScope/requestScope must be set" }
        val ctx = "context(${ctxParams.joinToString(", ")})"

        return buildString {
            appendLine("// Generated by kroom-velocity-l10n. Do not edit.")
            appendLine("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")")
            appendLine()
            appendLine("package $pkg")
            appendLine()
            appendLine("import org.apache.velocity.engine.jvm.vtlFile")
            appendLine()
            for (s in stubs) {
                appendLine(ctx)
                appendLine("private fun ${s.funName}(): String = vtlFile(\"${s.vtlPath}\")")
            }
            appendLine()
            appendLine("/** Render the compiled, translated template for [path] in [lang], or null if none. */")
            appendLine(ctx)
            appendLine("public fun renderPage(path: String, lang: String): String? = when (\"\$lang/\$path\") {")
            for (s in stubs) appendLine("    \"${s.key}\" -> ${s.funName}()")
            appendLine("    else -> null")
            appendLine("}")
        }
    }
}
